# action.yml
name: "CDK action"
description: "CDK action"
inputs:
  tags:
    description: "docker image tags"
    required: true
  context:
    description: "context for the docker build"
    required: false
  dockerfile:
    description: "The dockerfile. Default: Dockerfile"
    required: false
outputs:
  ouptut:
    description: "The command output"
runs:
  using: "docker"
  image: "Dockerfile"
  # args:
  #   - ${{ inputs.command }}
