# action.yml
name: "CDK action"
description: "CDK action"
inputs:
  tags:
    description: "docker image tags"
    required: true
outputs:
  ouptut:
    description: "The command output"
runs:
  using: "docker"
  image: "Dockerfile"
  # args:
  #   - ${{ inputs.command }}
