name: ECR
on:
  workflow_dispatch: {}

jobs:
  cdk_job:
    runs-on: ubuntu-latest
    name: ECR public action
    steps:
      - name: test
        id: test
        uses: pahud/ecr-public-action@beefcf7
        env:
          TAG_LATEST: public.ecr.aws/d7p2r8s3/busybox:latest
        # with:
        #   command: '--version'
#     - name: diff
#       id: diff
#       uses: pahud/awscdk-action@v0.1.0
#       with:
#         command: 'diff'
